//
//  NewsfeedModels.swift
//  VkNewsFeed
//
//  Created by Иван Абрамов on 02.09.2020.
//  Copyright (c) 2020 Иван Абрамов. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Model {
  // MARK: Use cases
  
    struct Request {
        enum RequestType {
            case getNewsFeed
            case getUser
            case revealPost(id: Int)
            case getOldFeed
            case performSearch(text: String)
            case cancelSearch
        }
    }
    struct Response {
        enum ResponseType {
            case presentNewsFeed(feed: FeedResponse, revealedPostIds: [Int])
            case presentUser(user: UserResponse)
            case displayFooterView
        }
    }
    struct ViewModel {
        enum ViewModelData {
            case displayNewsFeed(model: FeedViewModel)
            case displayUser(model: UserViewModel)
            case displayFooterView
        }
    }
}

struct UserViewModel: TitleViewViewModel {
    let photoURL: String?
    let screenName: String?
}

struct FeedViewModel {
    struct Cell: FeedCellViewModel {
        var postId: Int
        var iconUrlString: String
        var name: String
        var date: String
        var text: String?
        var likes: String?
        var comments: String?
        var shares: String?
        var views: String?
        var photoAttachements: [FeedCellPhotoAttachementViewModel]
        var linkAttachment: FeedCellLinkAttachmentViewModel?
        var sizes: FeedCellSizes
    }
    
    let cells: [Cell]
    let footerTitle: String?
    
    struct FeedCellPhotoAttachement: FeedCellPhotoAttachementViewModel {
        var photoURLString: String?
        var width: Int
        var height: Int
    }
    
    struct FeedCellLinkAttachement: FeedCellLinkAttachmentViewModel {
        var photoURLString: String?
        var linkTitle: String
        var url: String
    }
}

